/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.simpMusic;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Amplitude</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.simpMusic.Amplitude#getAmp <em>Amp</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.simpMusic.SimpMusicPackage#getAmplitude()
 * @model
 * @generated
 */
public interface Amplitude extends Modification
{
  /**
   * Returns the value of the '<em><b>Amp</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.simpMusic.AmpType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Amp</em>' attribute.
   * @see uk.ac.kcl.inf.simpMusic.AmpType
   * @see #setAmp(AmpType)
   * @see uk.ac.kcl.inf.simpMusic.SimpMusicPackage#getAmplitude_Amp()
   * @model
   * @generated
   */
  AmpType getAmp();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.simpMusic.Amplitude#getAmp <em>Amp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Amp</em>' attribute.
   * @see uk.ac.kcl.inf.simpMusic.AmpType
   * @see #getAmp()
   * @generated
   */
  void setAmp(AmpType value);

} // Amplitude
