/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.simpMusic;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Loop Note</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.simpMusic.LoopNote#getCount <em>Count</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.simpMusic.LoopNote#getNotes <em>Notes</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.simpMusic.SimpMusicPackage#getLoopNote()
 * @model
 * @generated
 */
public interface LoopNote extends Note
{
  /**
   * Returns the value of the '<em><b>Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Count</em>' attribute.
   * @see #setCount(int)
   * @see uk.ac.kcl.inf.simpMusic.SimpMusicPackage#getLoopNote_Count()
   * @model
   * @generated
   */
  int getCount();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.simpMusic.LoopNote#getCount <em>Count</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Count</em>' attribute.
   * @see #getCount()
   * @generated
   */
  void setCount(int value);

  /**
   * Returns the value of the '<em><b>Notes</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.simpMusic.Note}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Notes</em>' containment reference list.
   * @see uk.ac.kcl.inf.simpMusic.SimpMusicPackage#getLoopNote_Notes()
   * @model containment="true"
   * @generated
   */
  EList<Note> getNotes();

} // LoopNote
