/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.simpMusic;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.simpMusic.SimpMusicPackage
 * @generated
 */
public interface SimpMusicFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SimpMusicFactory eINSTANCE = uk.ac.kcl.inf.simpMusic.impl.SimpMusicFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Simple Music</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Simple Music</em>'.
   * @generated
   */
  SimpleMusic createSimpleMusic();

  /**
   * Returns a new object of class '<em>Note</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Note</em>'.
   * @generated
   */
  Note createNote();

  /**
   * Returns a new object of class '<em>Loop Note</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Loop Note</em>'.
   * @generated
   */
  LoopNote createLoopNote();

  /**
   * Returns a new object of class '<em>Solfege</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Solfege</em>'.
   * @generated
   */
  Solfege createSolfege();

  /**
   * Returns a new object of class '<em>Sleep</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sleep</em>'.
   * @generated
   */
  Sleep createSleep();

  /**
   * Returns a new object of class '<em>Solfege With Modification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Solfege With Modification</em>'.
   * @generated
   */
  SolfegeWithModification createSolfegeWithModification();

  /**
   * Returns a new object of class '<em>Modification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Modification</em>'.
   * @generated
   */
  Modification createModification();

  /**
   * Returns a new object of class '<em>Amplitude</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Amplitude</em>'.
   * @generated
   */
  Amplitude createAmplitude();

  /**
   * Returns a new object of class '<em>Timbre</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Timbre</em>'.
   * @generated
   */
  Timbre createTimbre();

  /**
   * Returns a new object of class '<em>Tone</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tone</em>'.
   * @generated
   */
  Tone createTone();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  SimpMusicPackage getSimpMusicPackage();

} //SimpMusicFactory
