/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.simpMusic;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.simpMusic.SimpMusicFactory
 * @model kind="package"
 * @generated
 */
public interface SimpMusicPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "simpMusic";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/inf/SimpMusic";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "simpMusic";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SimpMusicPackage eINSTANCE = uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.simpMusic.impl.SimpleMusicImpl <em>Simple Music</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.simpMusic.impl.SimpleMusicImpl
   * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getSimpleMusic()
   * @generated
   */
  int SIMPLE_MUSIC = 0;

  /**
   * The feature id for the '<em><b>Notes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_MUSIC__NOTES = 0;

  /**
   * The number of structural features of the '<em>Simple Music</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_MUSIC_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.simpMusic.impl.NoteImpl <em>Note</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.simpMusic.impl.NoteImpl
   * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getNote()
   * @generated
   */
  int NOTE = 1;

  /**
   * The number of structural features of the '<em>Note</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.simpMusic.impl.LoopNoteImpl <em>Loop Note</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.simpMusic.impl.LoopNoteImpl
   * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getLoopNote()
   * @generated
   */
  int LOOP_NOTE = 2;

  /**
   * The feature id for the '<em><b>Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_NOTE__COUNT = NOTE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Notes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_NOTE__NOTES = NOTE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Loop Note</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_NOTE_FEATURE_COUNT = NOTE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.simpMusic.impl.SolfegeImpl <em>Solfege</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.simpMusic.impl.SolfegeImpl
   * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getSolfege()
   * @generated
   */
  int SOLFEGE = 3;

  /**
   * The feature id for the '<em><b>Note</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOLFEGE__NOTE = NOTE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Solfege</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOLFEGE_FEATURE_COUNT = NOTE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.simpMusic.impl.SleepImpl <em>Sleep</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.simpMusic.impl.SleepImpl
   * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getSleep()
   * @generated
   */
  int SLEEP = 4;

  /**
   * The feature id for the '<em><b>Note</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLEEP__NOTE = NOTE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Sleep</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLEEP_FEATURE_COUNT = NOTE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.simpMusic.impl.SolfegeWithModificationImpl <em>Solfege With Modification</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.simpMusic.impl.SolfegeWithModificationImpl
   * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getSolfegeWithModification()
   * @generated
   */
  int SOLFEGE_WITH_MODIFICATION = 5;

  /**
   * The feature id for the '<em><b>Note</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOLFEGE_WITH_MODIFICATION__NOTE = NOTE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Mods</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOLFEGE_WITH_MODIFICATION__MODS = NOTE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Solfege With Modification</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOLFEGE_WITH_MODIFICATION_FEATURE_COUNT = NOTE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.simpMusic.impl.ModificationImpl <em>Modification</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.simpMusic.impl.ModificationImpl
   * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getModification()
   * @generated
   */
  int MODIFICATION = 6;

  /**
   * The number of structural features of the '<em>Modification</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFICATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.simpMusic.impl.AmplitudeImpl <em>Amplitude</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.simpMusic.impl.AmplitudeImpl
   * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getAmplitude()
   * @generated
   */
  int AMPLITUDE = 7;

  /**
   * The feature id for the '<em><b>Amp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AMPLITUDE__AMP = MODIFICATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Amplitude</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AMPLITUDE_FEATURE_COUNT = MODIFICATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.simpMusic.impl.TimbreImpl <em>Timbre</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.simpMusic.impl.TimbreImpl
   * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getTimbre()
   * @generated
   */
  int TIMBRE = 8;

  /**
   * The feature id for the '<em><b>Timbre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMBRE__TIMBRE = MODIFICATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Timbre</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMBRE_FEATURE_COUNT = MODIFICATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.simpMusic.impl.ToneImpl <em>Tone</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.simpMusic.impl.ToneImpl
   * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getTone()
   * @generated
   */
  int TONE = 9;

  /**
   * The feature id for the '<em><b>Tone</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TONE__TONE = MODIFICATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TONE__VAL = MODIFICATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Tone</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TONE_FEATURE_COUNT = MODIFICATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.simpMusic.Solfa <em>Solfa</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.simpMusic.Solfa
   * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getSolfa()
   * @generated
   */
  int SOLFA = 10;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.simpMusic.AmpType <em>Amp Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.simpMusic.AmpType
   * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getAmpType()
   * @generated
   */
  int AMP_TYPE = 11;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.simpMusic.TimbreType <em>Timbre Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.simpMusic.TimbreType
   * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getTimbreType()
   * @generated
   */
  int TIMBRE_TYPE = 12;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.simpMusic.ToneType <em>Tone Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.simpMusic.ToneType
   * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getToneType()
   * @generated
   */
  int TONE_TYPE = 13;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.simpMusic.SimpleMusic <em>Simple Music</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Music</em>'.
   * @see uk.ac.kcl.inf.simpMusic.SimpleMusic
   * @generated
   */
  EClass getSimpleMusic();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.simpMusic.SimpleMusic#getNotes <em>Notes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Notes</em>'.
   * @see uk.ac.kcl.inf.simpMusic.SimpleMusic#getNotes()
   * @see #getSimpleMusic()
   * @generated
   */
  EReference getSimpleMusic_Notes();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.simpMusic.Note <em>Note</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Note</em>'.
   * @see uk.ac.kcl.inf.simpMusic.Note
   * @generated
   */
  EClass getNote();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.simpMusic.LoopNote <em>Loop Note</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Loop Note</em>'.
   * @see uk.ac.kcl.inf.simpMusic.LoopNote
   * @generated
   */
  EClass getLoopNote();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.simpMusic.LoopNote#getCount <em>Count</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Count</em>'.
   * @see uk.ac.kcl.inf.simpMusic.LoopNote#getCount()
   * @see #getLoopNote()
   * @generated
   */
  EAttribute getLoopNote_Count();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.simpMusic.LoopNote#getNotes <em>Notes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Notes</em>'.
   * @see uk.ac.kcl.inf.simpMusic.LoopNote#getNotes()
   * @see #getLoopNote()
   * @generated
   */
  EReference getLoopNote_Notes();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.simpMusic.Solfege <em>Solfege</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Solfege</em>'.
   * @see uk.ac.kcl.inf.simpMusic.Solfege
   * @generated
   */
  EClass getSolfege();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.simpMusic.Solfege#getNote <em>Note</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Note</em>'.
   * @see uk.ac.kcl.inf.simpMusic.Solfege#getNote()
   * @see #getSolfege()
   * @generated
   */
  EAttribute getSolfege_Note();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.simpMusic.Sleep <em>Sleep</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sleep</em>'.
   * @see uk.ac.kcl.inf.simpMusic.Sleep
   * @generated
   */
  EClass getSleep();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.simpMusic.Sleep#getNote <em>Note</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Note</em>'.
   * @see uk.ac.kcl.inf.simpMusic.Sleep#getNote()
   * @see #getSleep()
   * @generated
   */
  EAttribute getSleep_Note();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.simpMusic.SolfegeWithModification <em>Solfege With Modification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Solfege With Modification</em>'.
   * @see uk.ac.kcl.inf.simpMusic.SolfegeWithModification
   * @generated
   */
  EClass getSolfegeWithModification();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.simpMusic.SolfegeWithModification#getNote <em>Note</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Note</em>'.
   * @see uk.ac.kcl.inf.simpMusic.SolfegeWithModification#getNote()
   * @see #getSolfegeWithModification()
   * @generated
   */
  EReference getSolfegeWithModification_Note();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.simpMusic.SolfegeWithModification#getMods <em>Mods</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Mods</em>'.
   * @see uk.ac.kcl.inf.simpMusic.SolfegeWithModification#getMods()
   * @see #getSolfegeWithModification()
   * @generated
   */
  EReference getSolfegeWithModification_Mods();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.simpMusic.Modification <em>Modification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Modification</em>'.
   * @see uk.ac.kcl.inf.simpMusic.Modification
   * @generated
   */
  EClass getModification();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.simpMusic.Amplitude <em>Amplitude</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Amplitude</em>'.
   * @see uk.ac.kcl.inf.simpMusic.Amplitude
   * @generated
   */
  EClass getAmplitude();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.simpMusic.Amplitude#getAmp <em>Amp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Amp</em>'.
   * @see uk.ac.kcl.inf.simpMusic.Amplitude#getAmp()
   * @see #getAmplitude()
   * @generated
   */
  EAttribute getAmplitude_Amp();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.simpMusic.Timbre <em>Timbre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Timbre</em>'.
   * @see uk.ac.kcl.inf.simpMusic.Timbre
   * @generated
   */
  EClass getTimbre();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.simpMusic.Timbre#getTimbre <em>Timbre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Timbre</em>'.
   * @see uk.ac.kcl.inf.simpMusic.Timbre#getTimbre()
   * @see #getTimbre()
   * @generated
   */
  EAttribute getTimbre_Timbre();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.simpMusic.Tone <em>Tone</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tone</em>'.
   * @see uk.ac.kcl.inf.simpMusic.Tone
   * @generated
   */
  EClass getTone();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.simpMusic.Tone#getTone <em>Tone</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tone</em>'.
   * @see uk.ac.kcl.inf.simpMusic.Tone#getTone()
   * @see #getTone()
   * @generated
   */
  EAttribute getTone_Tone();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.simpMusic.Tone#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see uk.ac.kcl.inf.simpMusic.Tone#getVal()
   * @see #getTone()
   * @generated
   */
  EAttribute getTone_Val();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.inf.simpMusic.Solfa <em>Solfa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Solfa</em>'.
   * @see uk.ac.kcl.inf.simpMusic.Solfa
   * @generated
   */
  EEnum getSolfa();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.inf.simpMusic.AmpType <em>Amp Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Amp Type</em>'.
   * @see uk.ac.kcl.inf.simpMusic.AmpType
   * @generated
   */
  EEnum getAmpType();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.inf.simpMusic.TimbreType <em>Timbre Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Timbre Type</em>'.
   * @see uk.ac.kcl.inf.simpMusic.TimbreType
   * @generated
   */
  EEnum getTimbreType();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.inf.simpMusic.ToneType <em>Tone Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Tone Type</em>'.
   * @see uk.ac.kcl.inf.simpMusic.ToneType
   * @generated
   */
  EEnum getToneType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SimpMusicFactory getSimpMusicFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.simpMusic.impl.SimpleMusicImpl <em>Simple Music</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.simpMusic.impl.SimpleMusicImpl
     * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getSimpleMusic()
     * @generated
     */
    EClass SIMPLE_MUSIC = eINSTANCE.getSimpleMusic();

    /**
     * The meta object literal for the '<em><b>Notes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIMPLE_MUSIC__NOTES = eINSTANCE.getSimpleMusic_Notes();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.simpMusic.impl.NoteImpl <em>Note</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.simpMusic.impl.NoteImpl
     * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getNote()
     * @generated
     */
    EClass NOTE = eINSTANCE.getNote();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.simpMusic.impl.LoopNoteImpl <em>Loop Note</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.simpMusic.impl.LoopNoteImpl
     * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getLoopNote()
     * @generated
     */
    EClass LOOP_NOTE = eINSTANCE.getLoopNote();

    /**
     * The meta object literal for the '<em><b>Count</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOP_NOTE__COUNT = eINSTANCE.getLoopNote_Count();

    /**
     * The meta object literal for the '<em><b>Notes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOP_NOTE__NOTES = eINSTANCE.getLoopNote_Notes();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.simpMusic.impl.SolfegeImpl <em>Solfege</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.simpMusic.impl.SolfegeImpl
     * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getSolfege()
     * @generated
     */
    EClass SOLFEGE = eINSTANCE.getSolfege();

    /**
     * The meta object literal for the '<em><b>Note</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOLFEGE__NOTE = eINSTANCE.getSolfege_Note();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.simpMusic.impl.SleepImpl <em>Sleep</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.simpMusic.impl.SleepImpl
     * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getSleep()
     * @generated
     */
    EClass SLEEP = eINSTANCE.getSleep();

    /**
     * The meta object literal for the '<em><b>Note</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SLEEP__NOTE = eINSTANCE.getSleep_Note();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.simpMusic.impl.SolfegeWithModificationImpl <em>Solfege With Modification</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.simpMusic.impl.SolfegeWithModificationImpl
     * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getSolfegeWithModification()
     * @generated
     */
    EClass SOLFEGE_WITH_MODIFICATION = eINSTANCE.getSolfegeWithModification();

    /**
     * The meta object literal for the '<em><b>Note</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SOLFEGE_WITH_MODIFICATION__NOTE = eINSTANCE.getSolfegeWithModification_Note();

    /**
     * The meta object literal for the '<em><b>Mods</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SOLFEGE_WITH_MODIFICATION__MODS = eINSTANCE.getSolfegeWithModification_Mods();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.simpMusic.impl.ModificationImpl <em>Modification</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.simpMusic.impl.ModificationImpl
     * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getModification()
     * @generated
     */
    EClass MODIFICATION = eINSTANCE.getModification();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.simpMusic.impl.AmplitudeImpl <em>Amplitude</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.simpMusic.impl.AmplitudeImpl
     * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getAmplitude()
     * @generated
     */
    EClass AMPLITUDE = eINSTANCE.getAmplitude();

    /**
     * The meta object literal for the '<em><b>Amp</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AMPLITUDE__AMP = eINSTANCE.getAmplitude_Amp();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.simpMusic.impl.TimbreImpl <em>Timbre</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.simpMusic.impl.TimbreImpl
     * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getTimbre()
     * @generated
     */
    EClass TIMBRE = eINSTANCE.getTimbre();

    /**
     * The meta object literal for the '<em><b>Timbre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIMBRE__TIMBRE = eINSTANCE.getTimbre_Timbre();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.simpMusic.impl.ToneImpl <em>Tone</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.simpMusic.impl.ToneImpl
     * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getTone()
     * @generated
     */
    EClass TONE = eINSTANCE.getTone();

    /**
     * The meta object literal for the '<em><b>Tone</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TONE__TONE = eINSTANCE.getTone_Tone();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TONE__VAL = eINSTANCE.getTone_Val();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.simpMusic.Solfa <em>Solfa</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.simpMusic.Solfa
     * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getSolfa()
     * @generated
     */
    EEnum SOLFA = eINSTANCE.getSolfa();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.simpMusic.AmpType <em>Amp Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.simpMusic.AmpType
     * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getAmpType()
     * @generated
     */
    EEnum AMP_TYPE = eINSTANCE.getAmpType();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.simpMusic.TimbreType <em>Timbre Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.simpMusic.TimbreType
     * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getTimbreType()
     * @generated
     */
    EEnum TIMBRE_TYPE = eINSTANCE.getTimbreType();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.simpMusic.ToneType <em>Tone Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.simpMusic.ToneType
     * @see uk.ac.kcl.inf.simpMusic.impl.SimpMusicPackageImpl#getToneType()
     * @generated
     */
    EEnum TONE_TYPE = eINSTANCE.getToneType();

  }

} //SimpMusicPackage
