/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.simpMusic;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sleep</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.simpMusic.Sleep#getNote <em>Note</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.simpMusic.SimpMusicPackage#getSleep()
 * @model
 * @generated
 */
public interface Sleep extends Note
{
  /**
   * Returns the value of the '<em><b>Note</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Note</em>' attribute.
   * @see #setNote(String)
   * @see uk.ac.kcl.inf.simpMusic.SimpMusicPackage#getSleep_Note()
   * @model
   * @generated
   */
  String getNote();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.simpMusic.Sleep#getNote <em>Note</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Note</em>' attribute.
   * @see #getNote()
   * @generated
   */
  void setNote(String value);

} // Sleep
