/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.simpMusic;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Solfege With Modification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.simpMusic.SolfegeWithModification#getNote <em>Note</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.simpMusic.SolfegeWithModification#getMods <em>Mods</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.simpMusic.SimpMusicPackage#getSolfegeWithModification()
 * @model
 * @generated
 */
public interface SolfegeWithModification extends Note
{
  /**
   * Returns the value of the '<em><b>Note</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Note</em>' containment reference.
   * @see #setNote(Solfege)
   * @see uk.ac.kcl.inf.simpMusic.SimpMusicPackage#getSolfegeWithModification_Note()
   * @model containment="true"
   * @generated
   */
  Solfege getNote();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.simpMusic.SolfegeWithModification#getNote <em>Note</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Note</em>' containment reference.
   * @see #getNote()
   * @generated
   */
  void setNote(Solfege value);

  /**
   * Returns the value of the '<em><b>Mods</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.simpMusic.Modification}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mods</em>' containment reference list.
   * @see uk.ac.kcl.inf.simpMusic.SimpMusicPackage#getSolfegeWithModification_Mods()
   * @model containment="true"
   * @generated
   */
  EList<Modification> getMods();

} // SolfegeWithModification
