/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.simpMusic;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Timbre</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.simpMusic.Timbre#getTimbre <em>Timbre</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.simpMusic.SimpMusicPackage#getTimbre()
 * @model
 * @generated
 */
public interface Timbre extends Modification
{
  /**
   * Returns the value of the '<em><b>Timbre</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.simpMusic.TimbreType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Timbre</em>' attribute.
   * @see uk.ac.kcl.inf.simpMusic.TimbreType
   * @see #setTimbre(TimbreType)
   * @see uk.ac.kcl.inf.simpMusic.SimpMusicPackage#getTimbre_Timbre()
   * @model
   * @generated
   */
  TimbreType getTimbre();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.simpMusic.Timbre#getTimbre <em>Timbre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Timbre</em>' attribute.
   * @see uk.ac.kcl.inf.simpMusic.TimbreType
   * @see #getTimbre()
   * @generated
   */
  void setTimbre(TimbreType value);

} // Timbre
