/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.simpMusic;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tone</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.simpMusic.Tone#getTone <em>Tone</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.simpMusic.Tone#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.simpMusic.SimpMusicPackage#getTone()
 * @model
 * @generated
 */
public interface Tone extends Modification
{
  /**
   * Returns the value of the '<em><b>Tone</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.simpMusic.ToneType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tone</em>' attribute.
   * @see uk.ac.kcl.inf.simpMusic.ToneType
   * @see #setTone(ToneType)
   * @see uk.ac.kcl.inf.simpMusic.SimpMusicPackage#getTone_Tone()
   * @model
   * @generated
   */
  ToneType getTone();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.simpMusic.Tone#getTone <em>Tone</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tone</em>' attribute.
   * @see uk.ac.kcl.inf.simpMusic.ToneType
   * @see #getTone()
   * @generated
   */
  void setTone(ToneType value);

  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(int)
   * @see uk.ac.kcl.inf.simpMusic.SimpMusicPackage#getTone_Val()
   * @model
   * @generated
   */
  int getVal();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.simpMusic.Tone#getVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #getVal()
   * @generated
   */
  void setVal(int value);

} // Tone
