/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class SimpMusicUiModule extends AbstractSimpMusicUiModule {
}
