/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SimpMusicIdeModule extends AbstractSimpMusicIdeModule {
}
