/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.inf.SimpMusicRuntimeModule;
import uk.ac.kcl.inf.SimpMusicStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SimpMusicIdeSetup extends SimpMusicStandaloneSetup {
  @Override
  public Injector createInjector() {
    SimpMusicRuntimeModule _simpMusicRuntimeModule = new SimpMusicRuntimeModule();
    SimpMusicIdeModule _simpMusicIdeModule = new SimpMusicIdeModule();
    return Guice.createInjector(Modules2.mixin(_simpMusicRuntimeModule, _simpMusicIdeModule));
  }
}
