/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SimpMusicRuntimeModule extends AbstractSimpMusicRuntimeModule {
}
