/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.inf.simpmusic.ui.internal.SimpmusicActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SimpMusicExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SimpmusicActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SimpmusicActivator activator = SimpmusicActivator.getInstance();
		return activator != null ? activator.getInjector(SimpmusicActivator.UK_AC_KCL_INF_SIMPMUSIC) : null;
	}

}
