/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.inf.parser.antlr.internal.InternalSimpMusicParser;
import uk.ac.kcl.inf.services.SimpMusicGrammarAccess;

public class SimpMusicParser extends AbstractAntlrParser {

	@Inject
	private SimpMusicGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSimpMusicParser createParser(XtextTokenStream stream) {
		return new InternalSimpMusicParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SimpleMusic";
	}

	public SimpMusicGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SimpMusicGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
