/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import uk.ac.kcl.inf.SimpMusicRuntimeModule
import uk.ac.kcl.inf.SimpMusicStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class SimpMusicIdeSetup extends SimpMusicStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new SimpMusicRuntimeModule, new SimpMusicIdeModule))
	}
	
}
