/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.inf.simpmusic.ui.internal.SimpmusicActivator;

public class SimpMusicUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SimpmusicActivator.getInstance().getInjector("uk.ac.kcl.inf.SimpMusic");
	}

}
